export const environment = {
    isDevelopment: true,
    routeReceptionistDashboard: 'receptionist-dashboard',
    routeSecurityOperatorDashboard: 'security-operator',
    routeHostAdminDashboard: 'host-admin-dashboard',
    routeSecurityConsoleDashboard: 'security-dashboard',
    routeHomeDashboard: '',
    httpBackendURI: "http://localhost:5120/",
    httpBackendTestEndPoint: "api/ng",
    httpBackendVisitorsReadPoint: '/api/visitors',
    httpBackendVisitorReadPoint: `/api/visitor/`,
    httpBackendVisitorUpdateEndPoint: '/api/visitor/update/',
    httpBackendVisitorCreateEndPoint: '/api/visitor/register',
    httpBackendHostsReadEndPoint: 'api/hosts',
    httpBackendHostReadEndPoint: 'api/host',
    httpBackendPassportReadEndpoint: 'api/reader/scan',
};
